services:
  postgres:
    image: postgres:17
    container_name: macrolens_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: macrolens
      POSTGRES_USER: macrolens
      POSTGRES_PASSWORD: macrolens_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: